name = "IntervalRootFinding"
uuid = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
version = "0.5.2"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ForwardDiff = "0.10"
IntervalArithmetic = "0.15, 0.16"
Polynomials = "0.5, 0.6"
StaticArrays = "0.11, 0.12"
julia = "1"

[extras]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Polynomials"]
